name: jacksi_task
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.0.5 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter: 
    sdk: flutter
  flutter_screenutil: ^5.8.4
  flutter_svg: ^2.0.7
  dio: ^5.3.2
  google_fonts: ^5.1.0

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets: 
    - assets/images/
    - assets/fonts/

  fonts:
  - family: Montserrat-Arabic
    fonts:
      - asset: assets/fonts/ArbFONTS-Montserrat-Arabic-Black.ttf
        weight: 900
      - asset: assets/fonts/ArbFONTS-Montserrat-Arabic-ExtraBold.ttf
        weight: 800
      - asset: assets/fonts/ArbFONTS-Montserrat-Arabic-Bold.ttf
        weight: 700
      - asset: assets/fonts/ArbFONTS-Montserrat-Arabic-SemiBold.ttf
        weight: 600
      - asset: assets/fonts/ArbFONTS-Montserrat-Arabic-Regular.ttf
        weight: 500
      - asset: assets/fonts/ArbFONTS-Montserrat-Arabic-Regular.ttf
        weight: 400
      - asset: assets/fonts/ArbFONTS-Montserrat-Arabic-Light.ttf
        weight: 300